export default [
    { path: '/dashboard', component: require('./components/Dashboard.vue').default },
    { path: '/profile', component: require('./components/Profile.vue').default },
    { path: '/developer', component: require('./components/Developer.vue').default },
    { path: '/users', component: require('./components/Users.vue').default },
    { path: '/products', component: require('./components/product/Products.vue').default },
    { path: '/product/tag', component: require('./components/product/Tag.vue').default },
    { path: '/product/category', component: require('./components/product/Category.vue').default },
    { path: '/product/section', component: require('./components/product/Tag.vue').default },
    { path: '/product/Blog', component: require('./components/product/Blog.vue').default },
    { path: '/product/Gallery', component: require('./components/product/Gallery.vue').default },
    { path: '/product/news', component: require('./components/product/News.vue').default },
    { path: '/order', component: require('./components/Orders.vue').default },
    { path: '*', component: require('./components/NotFound.vue').default },
];
